# This file was generated by GoReleaser. DO NOT EDIT.
class Keys < Formula
  desc ""
  homepage "https://keys.pub"
  version "0.0.43"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gabriel/keysd/releases/download/v0.0.43/keys_0.0.43_darwin_x86_64.tar.gz"
    sha256 "a7adceed4d39ad4070447c0f25ac57aa90bedf5c8bd889f566dfed02a6f6bd0b"
  elsif OS.linux?
  end

  def install
    bin.install "keys"
    bin.install "keysd"
  end
end
